<% jdbc = defined?(JRUBY_VERSION) ? 'jdbc' : '' %>

development:
   adapter: <%= jdbc %>mysql
   encoding: utf8
   host: db_server
   database: publications_dev
   username: user
   password: pass

test:
   adapter: <%= jdbc %>mysql
   encoding: utf8
   host: db_server
   database: publications_test
   username: user
   password: pass

production:
    adapter: <%= jdbc %>mysql
    encoding: utf8
    host: db_server
    #socket: /tmp/mysql.sock
    database: publications
    username: user
    password: pass
